name: kadena
description: Kadena SDK for Dart.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  bip32_ed25519: ^0.2.1
  bip39: ^1.0.6
  convert: ^3.0.1
  pinenacl: ^0.3.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1
